### ISSUE TITLE
Async Functions p.429

### ISSUE THREAD

**Issue by chinadbo** [msfrisbie/professional-javascript-for-web-developers#7]
```
async function foo() {
  console.log(2);
  console.log((await Promise.resolve(8)));
  console.log(9);
}

async function bar() {
  console.log(4);
  console.log((await 6));
  console.log(7);
}

console.log(1);
foo();
console.log(3);
bar();
console.log(5);
```
I have a different result
<img width="769" alt="image" src="https://user-images.githubusercontent.com/4602050/79181713-9ec56f00-7e3f-11ea-8a28-43d8cb4eca20.png">
could you please explain How it is works?

**Comment by msfrisbie** [comment]
This one took me a minute to figure out.

### Short answer: 

This code was correct when the book was written, but browsers have since changed their behavior.

### Longer answer:

When this chapter was written I was testing on Firefox v64 (and their contemporary vendor versions). If you install this [version of the browser](https://ftp.mozilla.org/pub/firefox/releases/64.0/), you will find that the example works correctly. 

I narrowed down the breaking release to Firefox 69, which was released a few months after this chapter was written and tested by the editing team. You will note that in the [release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69), under the "APIs" section there is a bullet "The Microtask API (WindowOrWorkerGlobalScope.queueMicrotask()) has been implemented". 

The [relevant section from the HTML specification](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#microtask-queuing) reads as follows:

> ...the best way of thinking about queueMicrotask() is as a mechanism for rearranging synchronous code, effectively placing the queued code immediately after the current task's worth of non-queued JavaScript.

The promise implementation in modern browsers makes use of the microtask API, which changes the order that this example executes in. Specifically, the example in the book makes use of the behavior where `await Promise.resolve(8)` would effectively delay this log statement two cycles - once for the `await`, once for the `Promise.resolve()`. Now that promises use the microtask queue, this is no longer the case, and therefore the log output in the book is incorrect.
